import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { Providers } from "~/app/providers";
import { NavigationMenu } from "~/app/_components/navigation-menu";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Providers headers={headers()}>
          <div className="min flex h-screen max-h-screen min-h-screen w-full flex-col overflow-hidden bg-gradient-to-b from-[#2e026d] to-[#15162c]">
            <div className="flex-1">{children}</div>
            <NavigationMenu />
          </div>
        </Providers>
      </body>
    </html>
  );
}
